const ONE_OCTAVE_NOTE = 12;
const REST_NOTE = 0;

const F_MIDI_NOTE = 65;
const E_FLAT_MIDI_NOTE = 63;
const D_FLAT_MIDI_NOTE = 61;
const B_FLAT_MIDI_NOTE = 58;
const A_FLAT_MIDI_NOTE = 56;

const TAE_NOTE = F_MIDI_NOTE;
const HWANG_NOTE = E_FLAT_MIDI_NOTE;
const MOO_NOTE = D_FLAT_MIDI_NOTE;
const YIM_NOTE = B_FLAT_MIDI_NOTE;
const JOONG_NOTE = A_FLAT_MIDI_NOTE;

const TAE_HIGH_NOTE = TAE_NOTE + ONE_OCTAVE_NOTE;
const HWANG_HIGH_NOTE = HWANG_NOTE + ONE_OCTAVE_NOTE;
const MOO_HIGH_NOTE = MOO_NOTE + ONE_OCTAVE_NOTE;
const YIM_HIGH_NOTE = YIM_NOTE + ONE_OCTAVE_NOTE;
const JOONG_HIGH_NOTE = JOONG_NOTE + ONE_OCTAVE_NOTE;
